package servlet.mvc.rest.model;
// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartId generated by hbm2java
 */
@Embeddable
public class CartId implements java.io.Serializable {

	private int cartId;
	private int uid;
	private int itemId;

	public CartId() {
	}

	public CartId(int cartId, int uid, int itemId) {
		this.cartId = cartId;
		this.uid = uid;
		this.itemId = itemId;
	}

	@Column(name = "CartId", nullable = false)
	public int getCartId() {
		return this.cartId;
	}

	public void setCartId(int cartId) {
		this.cartId = cartId;
	}

	@Column(name = "UId", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "ItemId", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CartId))
			return false;
		CartId castOther = (CartId) other;

		return (this.getCartId() == castOther.getCartId()) && (this.getUid() == castOther.getUid())
				&& (this.getItemId() == castOther.getItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCartId();
		result = 37 * result + this.getUid();
		result = 37 * result + this.getItemId();
		return result;
	}

}
