package servlet.mvc.rest.model;
// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "Cart", catalog = "FreeNForSale")
public class Cart implements java.io.Serializable {

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "CartId", column = @Column(name = "CartId", nullable = false)),
			@AttributeOverride(name = "UId", column = @Column(name = "UId", nullable = false)),
			@AttributeOverride(name = "ItemId", column = @Column(name = "ItemId", nullable = false)) })
	private CartId id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ItemId", nullable = false, insertable = false, updatable = false)
	private Inventory inventory;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "UId", nullable = false, insertable = false, updatable = false)
	private User user;
	
	@Column(name = "Quantity", nullable = false)
	private int quantity;
	
	@Column(name = "Amount", nullable = false, precision = 12, scale = 0)
	private float amount;
	
	@Column(name = "Completed", nullable = false)
	private byte completed;

	public Cart() {
	}

	public Cart(CartId id, Inventory inventory, User user, int quantity, float amount, byte completed) {
		this.id = id;
		this.inventory = inventory;
		this.user = user;
		this.quantity = quantity;
		this.amount = amount;
		this.completed = completed;
	}
	
	public CartId getId() {
		return this.id;
	}

	public void setId(CartId id) {
		this.id = id;
	}

	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	public byte getCompleted() {
		return this.completed;
	}

	public void setCompleted(byte completed) {
		this.completed = completed;
	}

}
