package servlet.mvc.rest.model;// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category", catalog = "FreeNForSale")
public class Category implements java.io.Serializable {

	private int categoryId;
	private String name;
	//private Set inventories = new HashSet(0);

	public Category() {
	}

	/*public Category(String name, Set inventories) {
		this.name = name;
		//this.inventories = inventories;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CategoryId", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}*/

}
