package servlet.mvc.rest.model;// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Finance generated by hbm2java
 */
@Entity
@Table(name = "finance", catalog = "freenforsale")
public class Finance implements java.io.Serializable {

	private FinanceId id;
	private User user;
	private int cvv;
	private Date expiryDate;
	private String cardType;

	public Finance() {
	}

	public Finance(FinanceId id, User user, int cvv, Date expiryDate, String cardType) {
		this.id = id;
		this.user = user;
		this.cvv = cvv;
		this.expiryDate = expiryDate;
		this.cardType = cardType;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "uid", column = @Column(name = "UId", nullable = false)),
			@AttributeOverride(name = "cardNo", column = @Column(name = "CardNo", nullable = false, length = 16)) })
	public FinanceId getId() {
		return this.id;
	}

	public void setId(FinanceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UId", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "CVV", nullable = false)
	public int getCvv() {
		return this.cvv;
	}

	public void setCvv(int cvv) {
		this.cvv = cvv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ExpiryDate", nullable = false, length = 10)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "CardType", nullable = false, length = 10)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

}
