package servlet.mvc.rest.model;
// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FinanceId generated by hbm2java
 */
@Embeddable
public class FinanceId implements java.io.Serializable {

	private int uid;
	private String cardNo;

	public FinanceId() {
	}

	public FinanceId(int uid, String cardNo) {
		this.uid = uid;
		this.cardNo = cardNo;
	}

	@Column(name = "UId", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "CardNo", nullable = false, length = 16)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FinanceId))
			return false;
		FinanceId castOther = (FinanceId) other;

		return (this.getUid() == castOther.getUid())
				&& ((this.getCardNo() == castOther.getCardNo()) || (this.getCardNo() != null
						&& castOther.getCardNo() != null && this.getCardNo().equals(castOther.getCardNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + (getCardNo() == null ? 0 : this.getCardNo().hashCode());
		return result;
	}

}
