package servlet.mvc.rest.model;
// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventoryimageId generated by hbm2java
 */
@Embeddable
public class InventoryimageId implements java.io.Serializable {

	@Column(name = "ItemId", nullable = false)
	private int itemId;

	@Column(name = "ImageId", nullable = false)
	private int imageId;

	public InventoryimageId() {
	}

	public InventoryimageId(int itemId, int imageId) {
		this.itemId = itemId;
		this.imageId = imageId;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryimageId))
			return false;
		InventoryimageId castOther = (InventoryimageId) other;

		return (this.getItemId() == castOther.getItemId()) && (this.getImageId() == castOther.getImageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemId();
		result = 37 * result + this.getImageId();
		return result;
	}

}
