package servlet.mvc.rest.model;
// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionId generated by hbm2java
 */
@Embeddable
public class TransactionId implements java.io.Serializable {

	@Column(name = "TId", nullable = false)
	private int tid;

	@Column(name = "UId", nullable = false)
	private int uid;

	@Column(name = "ItemId", nullable = false)
	private int itemId;

	public TransactionId() {
	}

	public TransactionId(int tid, int uid, int itemId) {
		this.tid = tid;
		this.uid = uid;
		this.itemId = itemId;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionId))
			return false;
		TransactionId castOther = (TransactionId) other;

		return (this.getTid() == castOther.getTid()) && (this.getUid() == castOther.getUid())
				&& (this.getItemId() == castOther.getItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getUid();
		result = 37 * result + this.getItemId();
		return result;
	}

}
