package servlet.mvc.rest.model;// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "freenforsale")
public class Transaction implements java.io.Serializable {

	private TransactionId id;
	private Inventory inventory;
	private User user;
	private Date purchaseTime;
	private int quantity;
	private float amount;
	private String paymentType;

	public Transaction() {
	}

	public Transaction(TransactionId id, Inventory inventory, User user, Date purchaseTime, int quantity, float amount,
			String paymentType) {
		this.id = id;
		this.inventory = inventory;
		this.user = user;
		this.purchaseTime = purchaseTime;
		this.quantity = quantity;
		this.amount = amount;
		this.paymentType = paymentType;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "tid", column = @Column(name = "TId", nullable = false)),
			@AttributeOverride(name = "uid", column = @Column(name = "UId", nullable = false)),
			@AttributeOverride(name = "itemId", column = @Column(name = "ItemId", nullable = false)) })
	public TransactionId getId() {
		return this.id;
	}

	public void setId(TransactionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ItemId", nullable = false, insertable = false, updatable = false)
	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UId", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PurchaseTime", nullable = false, length = 19)
	public Date getPurchaseTime() {
		return this.purchaseTime;
	}

	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Amount", nullable = false, precision = 12, scale = 0)
	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	@Column(name = "PaymentType", nullable = false, length = 10)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

}
