package servlet.mvc.rest.model;// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "FreeNForSale")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	public int getUid() {
		return this.uid;
	}
	
	public User(State state, UserLoginInfo userlogininfo, String name, Date bdate, String phone, String email,
			String street, String city, Integer zipcode, String sex, Long ssn, Date lastLoginTime, int failedAttempts) {
		super();
		this.state = state;
		this.name = name;
		this.bdate = bdate;
		this.phone = phone;
		this.email = email;
		this.street = street;
		this.city = city;
		this.zipcode = zipcode;
		this.sex = sex;
		this.ssn = ssn;
		this.lastLoginTime = lastLoginTime;
		this.failedAttempts = failedAttempts;
		this.userlogininfo = userlogininfo;
	}
	
	public User(UserLoginInfo userlogininfo, String name, String phone, String email, Date lastLoginTime,
			int failedAttempts) {
		this.userlogininfo = userlogininfo;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.lastLoginTime = lastLoginTime;
		this.failedAttempts = failedAttempts;
	}

	
	private static final long serialVersionUID = 166975415335427611L;
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userlogininfo"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "UId", unique = true, nullable = false)
	private int uid;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StateId")
	private State state;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private UserLoginInfo userlogininfo;
	
	@Column(name = "Name", nullable = false, length = 30)
	private String name;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "Bdate", length = 10)
	private Date bdate;
	
	@Column(name = "Phone", nullable = false)
	private String phone;
	
	@Column(name = "Email", nullable = false, length = 30)
	private String email;
	
	@Column(name = "Street", length = 25)
	private String street;
	
	@Column(name = "City", length = 15)
	private String city;
	
	@Column(name = "Zipcode")
	private Integer zipcode;
	
	@Column(name = "Sex", length = 1)
	private String sex;
	
	@Column(name = "SSN")
	private Long ssn;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLoginTime", nullable = false, length = 19)
	private Date lastLoginTime;
	
	@Column(name = "FailedAttempts", nullable = false)
	private int failedAttempts;
	
	@Column(name = "ProfilePhoto", length = 100)
	private String profilePhoto;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Finance> finances = new HashSet<Finance>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Transaction> transactions = new HashSet<Transaction>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Cart> carts = new HashSet<Cart>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Inventory> inventories = new HashSet<Inventory>(0);
	
	/*@OneToOne(fetch = FetchType.LAZY, mappedBy = "userByUid")
	private SellerReview sellerreviewByUid;*/
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByUid_1")
	private Set<SellerReview> sellerreviewsForUid = new HashSet<SellerReview>(0);

	public User() {
	}

	

	public void setUid(int uid) {
		this.uid = uid;
	}

	
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public UserLoginInfo getUserLoginInfo() {
		return this.userlogininfo;
	}

	public void setUserLoginInfo(UserLoginInfo userlogininfo) {
		this.userlogininfo = userlogininfo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public Date getBdate() {
		return this.bdate;
	}

	public void setBdate(Date bdate) {
		this.bdate = bdate;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Long getSsn() {
		return this.ssn;
	}

	public void setSsn(Long ssn) {
		this.ssn = ssn;
	}

	
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public int getFailedAttempts() {
		return this.failedAttempts;
	}

	public void setFailedAttempts(int failedAttempts) {
		this.failedAttempts = failedAttempts;
	}

	public String getProfilePhoto() {
		return this.profilePhoto;
	}

	public void setProfilePhoto(String profilePhoto) {
		this.profilePhoto = profilePhoto;
	}

	public Set<Finance> getFinances() {
		return this.finances;
	}

	public void setFinances(Set<Finance> finances) {
		this.finances = finances;
	}

	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	/*public SellerReview getSellerreviewByUid() {
		return this.sellerreviewByUid;
	}

	public void setSellerreviewByUid(SellerReview sellerreviewByUid) {
		this.sellerreviewByUid = sellerreviewByUid;
	}*/

	public Set<SellerReview> getSellerreviewsForUid() {
		return this.sellerreviewsForUid;
	}

	public void setSellerreviewsForUid(Set<SellerReview> sellerreviewsForUid) {
		this.sellerreviewsForUid = sellerreviewsForUid;
	}

}
