package servlet.mvc.rest.model;// default package
// Generated Apr 17, 2016 3:22:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userlogininfo generated by hbm2java
 */
@Entity
@Table(name = "userlogininfo", catalog = "freenforsale", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class Userlogininfo implements java.io.Serializable {

	private Integer uid;
	private String userName;
	private String password;
	private User user;

	public Userlogininfo() {
	}

	public Userlogininfo(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public Userlogininfo(String userName, String password, User user) {
		this.userName = userName;
		this.password = password;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UId", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 25)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userlogininfo")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
